// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const DEFAULT_SUPABASE_URL = "https://cwspwuvskyxbhoyhnbar.supabase.co";

function isValidHttpUrl(string: string | undefined): boolean {
  if (!string) return false;
  try {
    const url = new URL(string);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

function resolveSupabaseUrl(): string {
  const rawUrl =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env["VITE_SUPABASE_URL"]
      : undefined) ||
    (typeof process !== "undefined" && process.env ? process.env["SUPABASE_URL"] : undefined);

  if (isValidHttpUrl(rawUrl)) {
    return rawUrl!;
  }

  return DEFAULT_SUPABASE_URL;
}

function resolveSupabaseKey(): string {
  const rawKey =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"]
      : undefined) ||
    (typeof process !== "undefined" && process.env
      ? process.env["SUPABASE_PUBLISHABLE_KEY"]
      : undefined) ||
    "";

  if (!rawKey || rawKey === "VITE_SUPABASE_PUBLISHABLE_KEY" || rawKey.startsWith("your_")) {
    return "";
  }

  return rawKey;
}

export const isSupabaseConfigured = Boolean(resolveSupabaseKey());

function createSupabaseClient() {
  const SUPABASE_URL = resolveSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY =
    resolveSupabaseKey() || "sb_publishable_unconfigured_placeholder";

  if (!isSupabaseConfigured) {
    const message =
      "Supabase VITE_SUPABASE_PUBLISHABLE_KEY não configurada. Configure no Lovable ou nas variáveis de ambiente.";
    console.warn(`[Supabase] ${message}`);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
