// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwspwuvskyxbhoyhnbar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3c3B3dXZza3l4YmhveWhuYmFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzMTAyMTgsImV4cCI6MjEwMzg4NjIxOH0.OW5DtdV45e3-J-4Qjhn4iPVdjf8ZuFR50Jz4lAffrtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});